export const VITE_GET_PARTICIPANTS = import.meta.env.VITE_GET_PARTICIPANTS;
export const VITE_POST_PARTICIPANTS_SIGN_UP = import.meta.env
  .VITE_POST_PARTICIPANTS_SIGN_UP;
export const VITE_POST_PARTICIPANTS_SIGN_IN = import.meta.env
  .VITE_POST_PARTICIPANTS_SIGN_IN;
export const VITE_POST_PARTICIPATIONS_INSCRIBE = import.meta.env
  .VITE_POST_PARTICIPATIONS_INSCRIBE;
